### ISSUE TITLE
Request for Comprehensive Documentation

### ISSUE THREAD

**Issue by amritrout** [amritrout/StudySpace#2]
The project currently lacks detailed documentation, making it difficult for users to understand and contribute. We need comprehensive documentation.

**Comment by Sreenivasan2002** [comment]
I created a detailed README file that includes all necessary information such as project overview, prerequisites, installation steps, project structure, and usage instructions. This should make it much easier for users to understand and contribute to the project.

![image](https://github.com/user-attachments/assets/029de5b0-7165-4a3b-bacf-32796bb5ffd3)

**Comment by amritrout** [comment]
Thanks for the help
